You are given a python program that once exectued in the terminal with the command, python convertme.py , you must convert a decimal number that is generated by the program
Below is the output of the program after the correct binary representation of the number is given

------------------------------------------------------------------------

If 41 is in decimal base, what is it in binary base?
Answer: 101001
That is correct! Here's your flag: picoCTF{4ll_y0ur_b4535_722f6b39}

------------------------------------------------------------------------
